[project]
name = "machine-failures-detection-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "numpy>=2.2.2",
    "scikit-learn==1.5.2",
    "xgboost>=2.1.3",
]
